apiVersion: v1
kind: ConfigMap
metadata:
  name: thinkrank-config
  namespace: thinkrank
data:
  NODE_ENV: "production"
  API_GATEWAY_URL: "http://api-gateway:8000"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  GAME_SERVICE_URL: "http://game-service:3002"
  AI_SERVICE_URL: "http://ai-service:3003"
  SOCIAL_SERVICE_URL: "http://social-service:3004"
  REDIS_URL: "redis://redis:6379"
  DATABASE_URL: "postgresql://thinkrank:$(DATABASE_PASSWORD)@postgres:5432/thinkrank"