# External Secrets Operator Configuration
# This will replace all hardcoded secrets with AWS Secrets Manager integration
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: thinkrank
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secrets
  namespace: thinkrank
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: jwt-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: thinkrank/jwt
        property: secret
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: thinkrank/jwt
        property: refresh_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secrets
  namespace: thinkrank
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: database-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: thinkrank/database
        property: password
    - secretKey: SUPABASE_SERVICE_ROLE_KEY
      remoteRef:
        key: thinkrank/supabase
        property: service_role_key
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: thinkrank/redis
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: thinkrank
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: api-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: thinkrank/openai
        property: api_key
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: thinkrank/anthropic
        property: api_key
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: thinkrank/stripe
        property: secret_key
    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: thinkrank/sendgrid
        property: api_key