apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: thinkrank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - name: game-service
        image: thinkrank/game-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: thinkrank-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: thinkrank-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: thinkrank-config
              key: REDIS_URL
        - name: AI_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: thinkrank-config
              key: AI_SERVICE_URL
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: thinkrank-secrets
              key: DATABASE_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: thinkrank
spec:
  selector:
    app: game-service
  ports:
  - port: 3002
    targetPort: 3002