# SealedSecrets Configuration for Kubernetes
# These secrets are encrypted and safe to store in Git
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secrets-sealed
  namespace: thinkrank
spec:
  encryptedData:
    # These values will be replaced with actual encrypted secrets during deployment
    # Use: echo -n "actual-secret" | kubeseal --raw --from-file=/dev/stdin --namespace thinkrank --name jwt-secrets-sealed
    JWT_SECRET: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder - will be encrypted
    JWT_REFRESH_SECRET: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder - will be encrypted
  template:
    metadata:
      name: jwt-secrets
      namespace: thinkrank
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-secrets-sealed
  namespace: thinkrank
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder
    SUPABASE_SERVICE_ROLE_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder
    REDIS_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder
  template:
    metadata:
      name: database-secrets
      namespace: thinkrank
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets-sealed
  namespace: thinkrank
spec:
  encryptedData:
    OPENAI_API_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder
    ANTHROPIC_API_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder
    STRIPE_SECRET_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder
    SENDGRID_API_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGHzw... # Placeholder
  template:
    metadata:
      name: api-secrets
      namespace: thinkrank
    type: Opaque
---
# Key rotation policy - automated secret rotation
apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-rotation
  namespace: thinkrank
spec:
  schedule: "0 2 * * 0" # Weekly rotation at 2 AM Sunday
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: secret-rotator
            image: thinkrank/secret-rotator:latest
            env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: SECRET_NAMES
              value: "thinkrank/jwt,thinkrank/database,thinkrank/api"
            envFrom:
            - secretRef:
                name: aws-credentials
          restartPolicy: OnFailure