apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: thinkrank
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    rule_files:
      - /etc/prometheus/alerts.yml
    
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - thinkrank
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
      
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
      
      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service:3001']
        metrics_path: '/metrics'
      
      - job_name: 'game-service'
        static_configs:
          - targets: ['game-service:3002']
        metrics_path: '/metrics'
      
      - job_name: 'ai-service'
        static_configs:
          - targets: ['ai-service:3003']
        metrics_path: '/metrics'
      
      - job_name: 'social-service'
        static_configs:
          - targets: ['social-service:3004']
        metrics_path: '/metrics'
      
      - job_name: 'kong'
        static_configs:
          - targets: ['api-gateway:8001']
        metrics_path: '/metrics'
       # Game Service Integration Metrics
       - job_name: 'game-service-detailed'
         static_configs:
           - targets: ['game-service:3002']
         metrics_path: '/metrics'
         scrape_interval: 10s
         params:
           format: ['prometheus']
         metric_relabel_configs:
           - source_labels: [__name__]
             regex: 'game_(.*)'
             target_label: 'integration_type'
             replacement: '${1}'
           - source_labels: [__name__]
             regex: 'game_.*_(.*)'
             target_label: 'metric_category'
             replacement: '${1}'

       # Analytics Service Integration
       - job_name: 'analytics-integration'
         static_configs:
           - targets: ['analytics-service:3005']
         metrics_path: '/metrics'
         scrape_interval: 15s
         metric_relabel_configs:
           - source_labels: [__name__]
             regex: 'analytics_(.*)'
             target_label: 'analytics_metric'
             replacement: '${1}'

       # Social Service Integration
       - job_name: 'social-integration'
         static_configs:
           - targets: ['social-service:3004']
         metrics_path: '/metrics'
         scrape_interval: 15s
         metric_relabel_configs:
           - source_labels: [__name__]
             regex: 'social_(.*)'
             target_label: 'social_metric'
             replacement: '${1}'

       # AI Service Integration
       - job_name: 'ai-integration'
         static_configs:
           - targets: ['ai-service:3003']
         metrics_path: '/metrics'
         scrape_interval: 10s
         metric_relabel_configs:
           - source_labels: [__name__]
             regex: 'ai_(.*)'
             target_label: 'ai_metric'
             replacement: '${1}'

       # Cross-Service Integration Monitoring
       - job_name: 'integration-health'
         static_configs:
           - targets: ['game-service:3002', 'analytics-service:3005', 'social-service:3004', 'ai-service:3003']
         metrics_path: '/health'
         scrape_interval: 30s
         metric_relabel_configs:
           - source_labels: [__name__]
             regex: 'health_(.*)'
             target_label: 'health_component'
             replacement: '${1}'