apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: thinkrank
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    rule_files:
      - /etc/prometheus/alerts.yml
    
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - thinkrank
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
      
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
      
      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service:3001']
        metrics_path: '/metrics'
      
      - job_name: 'game-service'
        static_configs:
          - targets: ['game-service:3002']
        metrics_path: '/metrics'
      
      - job_name: 'ai-service'
        static_configs:
          - targets: ['ai-service:3003']
        metrics_path: '/metrics'
      
      - job_name: 'social-service'
        static_configs:
          - targets: ['social-service:3004']
        metrics_path: '/metrics'
      
      - job_name: 'kong'
        static_configs:
          - targets: ['api-gateway:8001']
        metrics_path: '/metrics'