apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: thinkrank
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: auth-service
        url: http://auth-service:3001
        routes:
          - name: auth-routes
            paths:
              - /api/auth
            strip_path: false
      - name: game-service
        url: http://game-service:3002
        routes:
          - name: game-routes
            paths:
              - /api/games
            strip_path: false
      - name: ai-service
        url: http://ai-service:3003
        routes:
          - name: ai-routes
            paths:
              - /api/ai
            strip_path: false
      - name: social-service
        url: http://social-service:3004
        routes:
          - name: social-routes
            paths:
              - /api/social
            strip_path: false
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600
      - name: rate-limiting
        config:
          minute: 60
          policy: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: thinkrank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: kong
        image: kong:3.4-alpine
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: /kong/declarative/kong.yml
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        volumeMounts:
        - name: kong-config
          mountPath: /kong/declarative
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: thinkrank
spec:
  selector:
    app: api-gateway
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
  - name: admin
    port: 8001
    targetPort: 8001