apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: thinkrank

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - auth-service.yaml
  - game-service.yaml
  - ai-service.yaml
  - social-service.yaml
  - api-gateway.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: thinkrank/auth-service
    newTag: latest
  - name: thinkrank/game-service
    newTag: latest
  - name: thinkrank/ai-service
    newTag: latest
  - name: thinkrank/social-service
    newTag: latest
  - name: thinkrank/frontend
    newTag: latest

commonLabels:
  app.kubernetes.io/name: thinkrank
  app.kubernetes.io/instance: production
  app.kubernetes.io/component: application
  app.kubernetes.io/part-of: thinkrank
  app.kubernetes.io/managed-by: kustomize