apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
  namespace: thinkrank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-service
  template:
    metadata:
      labels:
        app: social-service
    spec:
      containers:
      - name: social-service
        image: thinkrank/social-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: thinkrank-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: thinkrank-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: thinkrank-config
              key: REDIS_URL
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: thinkrank-secrets
              key: DATABASE_PASSWORD
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: thinkrank-secrets
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: thinkrank-secrets
              key: SUPABASE_ANON_KEY
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: thinkrank-secrets
              key: SUPABASE_SERVICE_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: social-service
  namespace: thinkrank
spec:
  selector:
    app: social-service
  ports:
  - port: 3004
    targetPort: 3004